🍳 Frontend:
- changed-files:
	- any-glob-to-any-file: 'Frontend/**/*'
🚀 Backend:
- changed-files:
	- any-glob-to-any-file: 'Backend/**/*'
🧢 Data:
- changed-files:
	- any-glob-to-any-file: 'Data/**/*'
✨ Feature:
	- head-branch: ['^feat', 'feat']
🐛 Bug Report:
	- head-branch: ['^hotfix', 'hotfix', '^fix', 'fix']
🛫 Release:
	- base-branch: 'main'