name: Frontend Deploy

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Frontend
    timeout-minutes: 10

    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Repository 체크아웃
        uses: actions/checkout@v3

      - name: Node 설정
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: pnpm 설치
        uses: pnpm/action-setup@v3
        with:
          version: 9.1.3

      - name: node_modules 캐싱
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 의존성 설치
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --no-frozen-lockfile

      - name: 클라이언트 빌드
        run: pnpm build

      - name: AWS CLI 설정
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: S3에 배포
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            build s3://indiero-bucket \
            --delete

      - name: Cloudfront invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} \
            --paths "/*"
