name: Frontend Playwright Test
on:
  push:
    branches: [main, develop]
    paths: Frontend/**
  pull_request:
    branches: [main, develop]
    paths: Frontend/**
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Frontend
    timeout-minutes: 10

    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.1.3

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Install Playwright with dependencies
        run: pnpm exec playwright install --with-deps

      - name: Run type checks
        run: pnpm exec tsc -p ./tests/tsconfig.json --noEmit

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ./playwright-report/
          retention-days: 30
