name: 'PR Labeler'
on:
  pull_request_target: # PR이 open(reopen) 되거나 새로운 commit push된 경우
    types: [opened, reopened, synchronize]

jobs:
  triage:
    permissions: # workflows 권한 지정
      contents: read # 레포 읽기 권한
      pull-requests: write # PR 쓰기 권한
    runs-on: ubuntu-latest
    steps:
      - name: Check Labels
        uses: actions/labeler@v5 # actions/labeler@v5 사용
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true # 규칙에 맞지 않는 라벨 제거
